server:
  port: 8080
  servlet:
    context-path: /wordtest

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file:
    path: